# Generated by Django 3.2.5 on 2021-07-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20210708_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'температура', 'verbose_name_plural': 'температура'},
        ),
    ]
